# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.cache/wt} [current_project]
set_property parent.project_path {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/new/Processor.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Instruction_Decoder_15.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Mux_2_to_1.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Register_1.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/OR_5.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/D_FF.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/AND_5.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Mux_8_way_1.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Register_Bank_8.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Mux_2_way_5.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Register_5.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Multiplier_5.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Decoder_2_to_4.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Mux_4_to_1.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/ALU.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/ADD_5.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Decoder_3_to_8.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Add_Sub_5.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Program_ROM_15.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/HA.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Mux_8_way_5.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/NOT_5.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Comp_1.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/FA.vhd}
  {E:/Advanced Nano Processor_final/project_AdvancedNano/project_AdvancedNano.srcs/sources_1/imports/new/Comp_5.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Processor -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Processor_utilization_synth.rpt -pb Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
