# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {G:/Vivado Projects/Advanced Nano Processor/Advanced Nano Processor.cache/wt} [current_project]
set_property parent.project_path {G:/Vivado Projects/Advanced Nano Processor/Advanced Nano Processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {g:/Vivado Projects/Advanced Nano Processor/Advanced Nano Processor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {G:/Vivado Projects/Basic processor components/D_FF.vhd}
  {G:/Vivado Projects/Basic processor components/Register_1.vhd}
  {G:/Vivado Projects/Basic processor components/Decoder_3_to_8.vhd}
  {G:/Vivado Projects/Basic processor components/Register_5.vhd}
  {G:/Vivado Projects/Basic processor components/Register_Bank_8.vhd}
  {G:/Vivado Projects/Basic processor components/Mux_2_to_1.vhd}
  {G:/Vivado Projects/Basic processor components/Decoder_2_to_4.vhd}
  {G:/Vivado Projects/Basic processor components/ADD_5.vhd}
  {G:/Vivado Projects/Basic processor components/HA.vhd}
  {G:/Vivado Projects/Basic processor components/FA.vhd}
  {G:/Vivado Projects/Basic processor components/Multiplier_5.vhd}
  {G:/Vivado Projects/Basic processor components/Comp_5.vhd}
  {G:/Vivado Projects/Basic processor components/AND_5.vhd}
  {G:/Vivado Projects/Basic processor components/OR_5.vhd}
  {G:/Vivado Projects/Basic processor components/Comp_1.vhd}
  {G:/Vivado Projects/Basic processor components/ALU.vhd}
  {G:/Vivado Projects/Basic processor components/Add_Sub_5.vhd}
  {G:/Vivado Projects/Basic processor components/NOT_5.vhd}
  {G:/Vivado Projects/Basic processor components/Mux_8_way_5.vhd}
  {G:/Vivado Projects/Basic processor components/Mux_8_way_1.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Multiplier_5 -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Multiplier_5.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Multiplier_5_utilization_synth.rpt -pb Multiplier_5_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
